### ISSUE TITLE
Integer URL paramters don't seem to work

### ISSUE THREAD

**Issue by Scimon** [croservices/cro-openapi-routes-from-definition#4]
Trying out the system, found that defining a parameter like so : 

```
      parameters:
        - in: path
          name: user_id
          description: User Id
          required: true
          schema:
            type: integer
```

Calling with a URL like `/api/user/1` returns a 404 and looking at the trace logs I see the error. 

`Request to /api/user/1 failed validation: validation of route segment 'user_id' schema failed at root: Not an integer`

I would expect this to match correctly in this case.
